# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Features 🎉
      labels:
        - enhancement
    - title: Bugs 🤖
      labels:
        - bug
    - title: Documentation 📖
      labels:
        - documentation 
    - title: Other Changes
      labels:
        - "*"
